import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,AnimatePresence,useMotionValue,useReducedMotion,useScroll,useSpring,useTransform} from 'motion/react';
import {Canvas,useFrame} from '@react-three/fiber';
import {Float,OrbitControls,Stars} from '@react-three/drei';
import * as THREE from 'three';
import {Search,MapPin,CalendarDays,Users,Languages,Star,Clock3,ShieldCheck,Wallet,Compass,ChevronRight,ArrowLeft,CheckCircle2,UserRound,Route,Menu,X,RefreshCw,Sparkles,CreditCard,Banknote,Globe2,Camera,Utensils,Landmark,Move3d,ArrowUpRight,Play,ArrowDown,Navigation,Heart,ScanLine,Layers3, Zap, BadgeCheck} from 'lucide-react';
import './styles.css';

const API='/api';
const fallbackGuides=[
{id:1,name:'Arun Kumar',city:'Chennai',languages:['English','Tamil','Hindi'],rating:4.9,reviews:128,experience:'7 years',price:1200,specialties:['Heritage','Food','Architecture'],bio:'Local historian who loves turning Chennai walks into stories.'},
{id:2,name:'Meena Ravi',city:'Chennai',languages:['English','Tamil','French'],rating:4.8,reviews:94,experience:'5 years',price:1500,specialties:['Culture','Temples','Shopping'],bio:'Friendly cultural guide specializing in first-time visitors.'},
{id:3,name:'Vikram S',city:'Chennai',languages:['English','Tamil','Telugu'],rating:4.7,reviews:76,experience:'4 years',price:1000,specialties:['Street Food','Local Life','Photography'],bio:'Photographer and food lover for authentic local experiences.'}
];

const INDIA_DESTINATIONS=[
{id:'chennai',name:'Chennai',state:'Tamil Nadu',region:'South',tag:'Coast · Culture',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Marina_beach%20chennai.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Marina_beach_chennai.jpg'},
{id:'mahabalipuram',name:'Mahabalipuram',state:'Tamil Nadu',region:'South',tag:'Heritage · Sea',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Shore_Temple_Mahabalipuram_Tamil-Nadu_India.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Shore_Temple_Mahabalipuram_Tamil-Nadu_India.jpg'},
{id:'madurai',name:'Madurai',state:'Tamil Nadu',region:'South',tag:'Temple · Food',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Meenakshi%20Temple.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Meenakshi_Temple.jpg'},
{id:'kochi',name:'Kochi',state:'Kerala',region:'South',tag:'Backwaters · Art',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Kerala_Backwater_.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Kerala_Backwater_.jpg'},
{id:'alleppey',name:'Alappuzha',state:'Kerala',region:'South',tag:'Backwaters · Slow travel',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Kerala_Backwater_.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Kerala_Backwater_.jpg'},
{id:'goa',name:'Goa',state:'Goa',region:'West',tag:'Beach · Nightlife',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Vagator%20Beach%2C%20Goa.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Vagator_Beach,_Goa.jpg'},
{id:'mumbai',name:'Mumbai',state:'Maharashtra',region:'West',tag:'City · Coast',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Mumbai_gateway_of_india.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Mumbai_gateway_of_india.jpg'},
{id:'udaipur',name:'Udaipur',state:'Rajasthan',region:'West',tag:'Lakes · Palaces',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Hawa_Mahal_in_Jaipur%2C_Rajasthan.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Hawa_Mahal_in_Jaipur,_Rajasthan.jpg'},
{id:'jaipur',name:'Jaipur',state:'Rajasthan',region:'West',tag:'Forts · Pink City',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Hawa_Mahal_in_Jaipur%2C_Rajasthan.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Hawa_Mahal_in_Jaipur,_Rajasthan.jpg'},
{id:'agra',name:'Agra',state:'Uttar Pradesh',region:'North',tag:'Taj Mahal · Heritage',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Taj_Mahal_India.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Taj_Mahal_India.jpg'},
{id:'varanasi',name:'Varanasi',state:'Uttar Pradesh',region:'North',tag:'Ghats · Spiritual',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Ganga%20Aarti%20Varanasi.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Ganga_Aarti_Varanasi.jpg'},
{id:'delhi',name:'Delhi',state:'Delhi',region:'North',tag:'History · Food',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Delhi%20red%20fort.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Delhi_red_fort.jpg'},
{id:'amritsar',name:'Amritsar',state:'Punjab',region:'North',tag:'Golden Temple · Food',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Golden%20Temple%20of%20Amritsar%2C%20India.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Golden_Temple_of_Amritsar,_India.jpg'},
{id:'leh',name:'Leh',state:'Ladakh',region:'North',tag:'Mountains · Monasteries',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Leh%20palace%20-%20Leh%20Ladakh.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Leh_palace_-_Leh_Ladakh.jpg'},
{id:'manali',name:'Manali',state:'Himachal Pradesh',region:'North',tag:'Himalayas · Adventure',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Leh%20palace%20-%20Leh%20Ladakh.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Leh_palace_-_Leh_Ladakh.jpg'},
{id:'kolkata',name:'Kolkata',state:'West Bengal',region:'East',tag:'Colonial · Culture',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Victoria%20Memorial%2C%20Kolkata%20India.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Victoria_Memorial,_Kolkata_India.jpg'},
{id:'darjeeling',name:'Darjeeling',state:'West Bengal',region:'East',tag:'Tea · Toy Train',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Darjeeling%20Himalayan%20Railway%2Ctoy%20train%20%284%29.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Darjeeling_Himalayan_Railway,toy_train_(4).jpg'},
{id:'konark',name:'Konark',state:'Odisha',region:'East',tag:'Sun Temple · Heritage',image:'https://commons.wikimedia.org/wiki/Special:FilePath/KONARK%20Sun%20Temple.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:KONARK_Sun_Temple.jpg'},
{id:'hampi',name:'Hampi',state:'Karnataka',region:'South',tag:'Ruins · History',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Hampi%20virupaksha%20temple.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Hampi_virupaksha_temple.jpg'},
{id:'mysuru',name:'Mysuru',state:'Karnataka',region:'South',tag:'Palace · Culture',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Mysore%20Palace%2C%20Mysore%2C%20Karnataka.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Mysore_Palace,_Mysore,_Karnataka.jpg'},
{id:'hyderabad',name:'Hyderabad',state:'Telangana',region:'South',tag:'Charminar · Biryani',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Charminar%2C%20Hyderabad%2C%20Telengana.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Charminar,_Hyderabad,_Telengana.jpg'},
{id:'sanchi',name:'Sanchi',state:'Madhya Pradesh',region:'Central',tag:'Buddhist · Heritage',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Stupa%20of%20Sanchi.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Stupa_of_Sanchi.jpg'},
{id:'bengaluru',name:'Bengaluru',state:'Karnataka',region:'South',tag:'Design · Cafés',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Mysore%20Palace%2C%20Mysore%2C%20Karnataka.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Mysore_Palace,_Mysore,_Karnataka.jpg'},
{id:'puducherry',name:'Puducherry',state:'Puducherry',region:'South',tag:'French Quarter · Coast',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Marina%20beach%20chennai.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Marina_beach_Chennai.jpg'},
{id:'rishikesh',name:'Rishikesh',state:'Uttarakhand',region:'North',tag:'Yoga · River',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Leh%20palace%20-%20Leh%20Ladakh.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Leh_palace_-_Leh_Ladakh.jpg'},
{id:'ahmedabad',name:'Ahmedabad',state:'Gujarat',region:'West',tag:'Heritage · Food',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Taj_Mahal_India.jpg?width=1400',source:'https://commons.wikimedia.org/wiki/File:Taj_Mahal_India.jpg'}
];
const imageForPlace=name=>{const q=String(name).toLowerCase();const hit=INDIA_DESTINATIONS.find(d=>q.includes(d.name.toLowerCase())||d.name.toLowerCase().includes(q));return hit?.image||INDIA_DESTINATIONS[0].image};

// Real motion clips from Wikimedia Commons. These are short public/CC-licensed clips,
// not a live webcam feed. They are shown as muted looping "live moments" in place pages.
const MOTION_MEDIA={
 kochi:{video:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Athirappilly_Waterfalls_video_03.webm',source:'https://commons.wikimedia.org/wiki/File:Athirappilly_Waterfalls_video_03.webm',caption:'Water flowing at Athirappilly Falls · Kochi region'},
 goa:{video:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Aguada_beach,_Goa.webm',source:'https://commons.wikimedia.org/wiki/File:Aguada_beach,_Goa.webm',caption:'Waves moving at Aguada Beach'},
 varanasi:{video:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ganga_aarti_at_Varanasi.webm',source:'https://commons.wikimedia.org/wiki/File:Ganga_aarti_at_Varanasi.webm',caption:'Evening Ganga Aarti in Varanasi'},
 hampi:{video:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Destination_-_Hampi_-_India.webm',source:'https://commons.wikimedia.org/wiki/File:Destination_-_Hampi_-_India.webm',caption:'Moving scenes from Hampi'},
 rishikesh:{video:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ganga_Aarti_at_Rishikesh.webm',source:'https://commons.wikimedia.org/wiki/File:Ganga_Aarti_at_Rishikesh.webm',caption:'Ganga Aarti at Rishikesh'}
};
const commonsCache=new Map();
async function fetchCommonsMedia(place){
 const key=place.id||place.name;
 if(commonsCache.has(key)) return commonsCache.get(key);
 const url=new URL('https://commons.wikimedia.org/w/api.php');
 url.searchParams.set('action','query');url.searchParams.set('format','json');url.searchParams.set('origin','*');
 url.searchParams.set('generator','search');url.searchParams.set('gsrnamespace','6');url.searchParams.set('gsrlimit','10');
 url.searchParams.set('gsrsearch',`${place.name} ${place.state||''} India`);
 url.searchParams.set('prop','imageinfo');url.searchParams.set('iiprop','url|mime|thumbmime|mediatype');url.searchParams.set('iiurlwidth','1200');
 try{
  const r=await fetch(url); const data=await r.json();
  const pages=Object.values(data?.query?.pages||{});
  const media=pages.map(x=>({title:x.title,image:x.imageinfo?.[0]?.thumburl||x.imageinfo?.[0]?.url,mime:x.imageinfo?.[0]?.mime||'',source:`https://commons.wikimedia.org/wiki/${encodeURIComponent(x.title).replace(/%3A/g,':')}`})).filter(x=>x.image&&x.mime.startsWith('image/')).slice(0,6);
  commonsCache.set(key,media); return media;
 }catch{return []}
}
function SmartPlaceImage({place,className='',alt='',loading='lazy'}){
 const [src,setSrc]=useState(place.image);
 useEffect(()=>{let live=true;fetchCommonsMedia(place).then(items=>{if(live&&items[0]?.image)setSrc(items[0].image)});return()=>{live=false}},[place.id]);
 return <img className={className} src={src} alt={alt||place.name} loading={loading} onError={e=>{if(e.currentTarget.src!==place.image)e.currentTarget.src=place.image}}/>;
}

const fallbackPackages=[
{id:1,title:'Chennai Heritage Day',city:'Chennai',duration:'1 day',price:299,places:['Fort St. George','Kapaleeshwarar Temple','San Thome Basilica'],type:'Heritage'},
{id:2,title:'Madurai Temple & Food Trail',city:'Madurai',duration:'1 day',price:349,places:['Meenakshi Amman Temple','Puthu Mandapam','Jigarthanda Trail'],type:'Culture'},
{id:3,title:'Kerala Backwater Escape',city:'Kochi',duration:'2 days',price:599,places:['Fort Kochi','Alleppey Backwaters','Mattancherry'],type:'Nature'},
{id:4,title:'Goa Coast & Old Town',city:'Goa',duration:'2 days',price:499,places:['Vagator Beach','Fontainhas','Old Goa'],type:'Sightseeing'},
{id:5,title:'Mumbai Icons',city:'Mumbai',duration:'1 day',price:399,places:['Gateway of India','Colaba','Marine Drive'],type:'City'},
{id:6,title:'Jaipur Pink City',city:'Jaipur',duration:'2 days',price:549,places:['Hawa Mahal','Amber Fort','City Palace'],type:'Heritage'},
{id:7,title:'Agra Taj Story',city:'Agra',duration:'1 day',price:449,places:['Taj Mahal','Agra Fort','Mehtab Bagh'],type:'Heritage'},
{id:8,title:'Varanasi by the Ganges',city:'Varanasi',duration:'2 days',price:499,places:['Dashashwamedh Ghat','Ganga Aarti','Old City Lanes'],type:'Spiritual'},
{id:9,title:'Delhi History Loop',city:'Delhi',duration:'2 days',price:449,places:['Red Fort','India Gate','Old Delhi Food Walk'],type:'Heritage'},
{id:10,title:'Amritsar Soul & Flavours',city:'Amritsar',duration:'1 day',price:399,places:['Golden Temple','Jallianwala Bagh','Local Food Trail'],type:'Culture'},
{id:11,title:'Hampi Time Machine',city:'Hampi',duration:'2 days',price:499,places:['Virupaksha Temple','Vittala Temple','Hampi Bazaar'],type:'Heritage'},
{id:12,title:'Mysuru Royal Weekend',city:'Mysuru',duration:'2 days',price:449,places:['Mysore Palace','Devaraja Market','Chamundi Hills'],type:'Culture'},
{id:13,title:'Hyderabad Charminar Nights',city:'Hyderabad',duration:'1 day',price:349,places:['Charminar','Laad Bazaar','Old City Biryani Trail'],type:'Food'},
{id:14,title:'Leh High-Altitude Escape',city:'Leh',duration:'3 days',price:799,places:['Leh Palace','Shanti Stupa','Old Leh Market'],type:'Adventure'},
{id:15,title:'Kolkata Culture Circuit',city:'Kolkata',duration:'2 days',price:449,places:['Victoria Memorial','College Street','Kumartuli'],type:'Culture'},
{id:16,title:'Darjeeling Tea & Toy Train',city:'Darjeeling',duration:'2 days',price:599,places:['Tiger Hill','Tea Estates','Toy Train'],type:'Nature'},
{id:17,title:'Konark Heritage Trail',city:'Konark',duration:'1 day',price:349,places:['Sun Temple','Chandrabhaga Beach','Puri Coast'],type:'Heritage'},
{id:18,title:'Sanchi Buddhist Trail',city:'Sanchi',duration:'1 day',price:299,places:['Great Stupa','Ashoka Pillar','Sanchi Museum'],type:'Heritage'}
];

function GlobeScene(){
 const globe=useRef();
 useFrame((_,d)=>{if(globe.current){globe.current.rotation.y+=d*.08;globe.current.rotation.x=Math.sin(Date.now()/5000)*.04}});
 return <>
  <ambientLight intensity={1.5}/><directionalLight position={[3,4,5]} intensity={3}/><pointLight position={[-4,-2,3]} color="#6ef2d8" intensity={8}/>
  <Stars radius={9} depth={4} count={700} factor={2} saturation={0} fade speed={.4}/>
  <Float speed={1.3} rotationIntensity={.15} floatIntensity={.5}>
   <group ref={globe}>
    <mesh><icosahedronGeometry args={[1.62,5]}/><meshStandardMaterial color="#0b8079" roughness={.34} metalness={.38} emissive="#063c3a" emissiveIntensity={.28}/></mesh>
    <mesh scale={1.02}><icosahedronGeometry args={[1.62,5]}/><meshBasicMaterial color="#74f1df" wireframe transparent opacity={.13}/></mesh>
    <mesh scale={1.08}><sphereGeometry args={[1.62,48,48]}/><meshBasicMaterial color="#63ead7" transparent opacity={.08} side={THREE.BackSide}/></mesh>
    {[0,1,2,3,4].map(i=><mesh key={i} rotation={[Math.PI/2,0,i*Math.PI/5]}><torusGeometry args={[1.82,.008,8,80]}/><meshBasicMaterial color="#6ef2d8" transparent opacity={.28}/></mesh>)}
    <mesh position={[.72,.56,1.38]}><sphereGeometry args={[.065,16,16]}/><meshBasicMaterial color="#ff9a78"/></mesh>
   </group>
  </Float>
  <OrbitControls enableZoom={false} enablePan={false} autoRotate autoRotateSpeed={.35} minPolarAngle={Math.PI/2.7} maxPolarAngle={Math.PI/1.9}/>
 </>
}

function MagneticButton({children,className='',onClick,type='button'}){
 const x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:280,damping:22}),sy=useSpring(y,{stiffness:280,damping:22});
 return <motion.button type={type} className={className} style={{x:sx,y:sy}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.16);y.set((e.clientY-r.top-r.height/2)*.16)}} onMouseLeave={()=>{x.set(0);y.set(0)}} onClick={onClick}>{children}</motion.button>
}
function Reveal({children,className=''}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:35}} whileInView={reduce?{}:{opacity:1,y:0}} viewport={{once:true,amount:.16}} transition={{duration:.7,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function CustomCursor(){
 const x=useMotionValue(-100),y=useMotionValue(-100),sx=useSpring(x,{stiffness:520,damping:42,mass:.35}),sy=useSpring(y,{stiffness:520,damping:42,mass:.35});
 const [active,setActive]=useState(false),[label,setLabel]=useState('');
 useEffect(()=>{
  const move=e=>{x.set(e.clientX);y.set(e.clientY)};
  const over=e=>{const el=e.target?.closest?.('button,a,input,select,[data-cursor]');if(el){setActive(true);setLabel(el.dataset?.cursor||((el.tagName==='INPUT'||el.tagName==='SELECT')?'SELECT':'OPEN'))}else{setActive(false);setLabel('')}};
  const out=e=>{if(!e.relatedTarget){setActive(false);setLabel('')}};
  window.addEventListener('mousemove',move,{passive:true});document.addEventListener('mouseover',over,{passive:true});document.addEventListener('mouseout',out,{passive:true});
  return()=>{window.removeEventListener('mousemove',move);document.removeEventListener('mouseover',over);document.removeEventListener('mouseout',out)};
 },[]);
 return <motion.div className={'customCursor '+(active?'cursorActive':'')} style={{x:sx,y:sy}} aria-hidden="true"><span className="cursorRing"><i/><b>{label}</b></span><span className="cursorDot"/></motion.div>
}

function App(){
 const [screen,setScreen]=useState('home'),[guides,setGuides]=useState([]),[packages,setPackages]=useState([]),[api,setApi]=useState('checking'),[filters,setFilters]=useState({destination:'Chennai',date:'',people:2,language:'English'}),[guide,setGuide]=useState(null),[pkg,setPkg]=useState(null),[selectedPlace,setSelectedPlace]=useState(null),[duration,setDuration]=useState(2),[booking,setBooking]=useState(null),[toast,setToast]=useState(''),[menu,setMenu]=useState(false),[paying,setPaying]=useState(false);
 const {scrollYProgress}=useScroll(); const progress=useSpring(scrollYProgress,{stiffness:120,damping:24});
 const load=async()=>{try{const [g,p,h]=await Promise.all([fetch(API+'/guides?destination='+encodeURIComponent(filters.destination)),fetch(API+'/packages'),fetch(API+'/health')]);setGuides(await g.json());setPackages(await p.json());setApi((await h.json()).ok?'online':'offline')}catch{setGuides(fallbackGuides);setPackages(fallbackPackages);setApi('offline')}};
 useEffect(()=>{load()},[]);
 const go=s=>{setScreen(s);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})};
 const selectPlace=d=>{setSelectedPlace(d);setFilters({...filters,destination:d.name});go('place')};
 const createBooking=async(kind)=>{const body={kind,touristName:'Demo Tourist',touristEmail:'tourist@example.com',destination:filters.destination,tourDate:filters.date,people:filters.people,guideId:kind==='guide'?guide.id:null,packageId:kind==='package'?pkg.id:null,durationHours:kind==='guide'?duration:1};setPaying(true);try{const r=await fetch(API+'/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);await startPayment(d,kind)}catch(e){setToast(e.message)}finally{setPaying(false)}};
 const startPayment=async(bookingData,kind)=>{const r=await fetch(API+'/payments/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookingCode:bookingData.bookingCode})});const order=await r.json();if(!r.ok)throw Error(order.error||'Could not create payment order');if(order.demo){setBooking({...bookingData,title:kind==='guide'?guide.name:pkg.title,kind,paymentMode:'demo'});go('confirmation');return}if(!window.Razorpay)throw Error('Razorpay checkout did not load. Refresh and try again.');const options={key:order.keyId,amount:order.amount,currency:order.currency,name:'LocalLoop',description:kind==='guide'?`10% guide advance • ${guide.name}`:`100% package payment • ${pkg.title}`,order_id:order.orderId,handler:async response=>{const vr=await fetch(API+'/payments/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookingCode:bookingData.bookingCode,...response})});const vd=await vr.json();if(!vr.ok)throw Error(vd.error||'Payment verification failed');setBooking({...bookingData,title:kind==='guide'?guide.name:pkg.title,kind,paymentMode:'razorpay'});go('confirmation')},modal:{ondismiss:()=>setToast('Payment window closed. Booking remains pending until payment succeeds.')},theme:{color:'#0b8079'}};new window.Razorpay(options).open()};
 return <div className="app"><CustomCursor/><motion.div className="scrollProgress" style={{scaleX:progress}}/><div className="ambient ambientA"/><div className="ambient ambientB"/><div className="noise"/>
 <header className="nav"><button className="brand" onClick={()=>go('home')}><span className="logo"><Compass/></span><span>Local<span>Loop</span></span></button><div className="navPill"><span className={api}></span>{api==='online'?'Live systems':'Connecting'}</div><nav className={menu?'open':''}><button className={screen==='home'?'active':''} onClick={()=>go('home')}>Discover</button><button onClick={()=>go('guides')}>Guides</button><button onClick={()=>go('packages')}>Journeys</button><button onClick={()=>go('india')}>India</button><button onClick={()=>go('become')}>Become a guide</button></nav><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><MagneticButton className="navCta" onClick={()=>go('choose')}>Start exploring <ArrowUpRight/></MagneticButton></header>
 {toast&&<motion.div className="toast" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}}><span>{toast}</span><button onClick={()=>setToast('')}>×</button></motion.div>}
 {paying&&<div className="payOverlay"><motion.div className="payModal" initial={{scale:.9,opacity:0}} animate={{scale:1,opacity:1}}><div className="paymentOrb"><div/></div><h3>Preparing secure checkout</h3><p>LocalLoop is creating your protected payment session.</p></motion.div></div>}
 <AnimatePresence mode="wait">{screen==='home'&&<Home key="home" filters={filters} setFilters={setFilters} search={()=>go('choose')} go={go} selectPlace={selectPlace}/>} {screen==='choose'&&<Choose key="choose" go={go}/>} {screen==='guides'&&<Guides key="guides" data={guides} choose={g=>{setGuide(g);setDuration(2);go('guide')}}/>} {screen==='guide'&&guide&&<Guide key="guide" g={guide} duration={duration} setDuration={setDuration} back={()=>go('guides')} confirm={()=>createBooking('guide')}/>} {screen==='packages'&&<Packages key="packages" data={packages} choose={p=>{setPkg(p);go('package')}}/>} {screen==='india'&&<IndiaExplorer key="india" destinations={INDIA_DESTINATIONS} select={selectPlace}/>} {screen==='place'&&selectedPlace&&<PlaceDetail key="place" place={selectedPlace} back={()=>go('india')} explore={()=>go('choose')}/>} {screen==='package'&&pkg&&<Package key="package" p={pkg} people={filters.people} back={()=>go('packages')} confirm={()=>createBooking('package')}/>} {screen==='confirmation'&&booking&&<Confirmation key="confirmation" b={booking} go={go}/>} {screen==='become'&&<Become key="become" onCreated={()=>{load();go('guides')}}/>}</AnimatePresence>
 <footer><div><b>LocalLoop</b><span>Travel local. Feel local.</span></div><div><span>Guides · Digital journeys · Secure checkout</span><small>Guide: 10% online · Package: 100% online</small></div></footer>
 </div>
}

function SearchBox({filters,setFilters,search}){return <motion.form className="searchDock" onSubmit={e=>{e.preventDefault();search()}} initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.45,duration:.7}}><label><MapPin/><span>Destination</span><input list="india-destinations" value={filters.destination} onChange={e=>setFilters({...filters,destination:e.target.value})}/><datalist id="india-destinations">{INDIA_DESTINATIONS.map(d=><option key={d.id} value={d.name}>{d.state}</option>)}</datalist></label><label><CalendarDays/><span>Date</span><input required type="date" value={filters.date} onChange={e=>setFilters({...filters,date:e.target.value})}/></label><label><Users/><span>People</span><input type="number" min="1" max="20" value={filters.people} onChange={e=>setFilters({...filters,people:+e.target.value})}/></label><label><Languages/><span>Language</span><select value={filters.language} onChange={e=>setFilters({...filters,language:e.target.value})}><option>English</option><option>Tamil</option><option>Hindi</option><option>French</option><option>Telugu</option><option>All</option></select></label><MagneticButton type="submit" className="searchButton"><Search/><span>Discover</span><ArrowUpRight/></MagneticButton></motion.form>}
function Home({filters,setFilters,search,go,selectPlace}){const {scrollY}=useScroll();const heroY=useTransform(scrollY,[0,700],[0,130]);return <main>
 <section className="heroPro"><motion.div className="heroCopyPro" style={{y:heroY}}><div className="eyebrow"><Sparkles/> THE LOCAL WAY TO TRAVEL</div><h1>Don't just visit.<br/><span>Belong there.</span></h1><p>Find the people, places and stories that turn a destination into <strong>your</strong> destination.</p><div className="heroActions"><MagneticButton className="heroCta" onClick={()=>go('choose')}>Explore Chennai <ArrowUpRight/></MagneticButton><button className="playBtn" onClick={()=>document.getElementById('why').scrollIntoView({behavior:'smooth'})}><span><Play fill="currentColor"/></span> See how it works</button></div><div className="proofRow"><div className="avatarStack"><i>AK</i><i>MR</i><i>VS</i><b>+128</b></div><span><strong>Local hosts</strong><br/>ready to make it personal</span></div></motion.div>
 <div className="heroVisual"><div className="visualBadge badgeTop"><Navigation/> <span>Chennai</span><small>13.08° N · 80.27° E</small></div><div className="webgl"><Canvas camera={{position:[0,0,5.2],fov:42}} dpr={[1,1.5]}><GlobeScene/></Canvas></div><motion.div className="orbitCard ocA" animate={{y:[0,-12,0],rotate:[-2,1,-2]}} transition={{duration:5,repeat:Infinity,ease:'easeInOut'}}><span>01</span><div><b>Meet a local</b><small>human stories</small></div></motion.div><motion.div className="orbitCard ocB" animate={{y:[0,10,0],rotate:[2,-1,2]}} transition={{duration:6,repeat:Infinity,ease:'easeInOut'}}><span>02</span><div><b>Go off-script</b><small>hidden corners</small></div></motion.div><div className="visualHint"><Move3d/> Drag the globe</div></div>
 <SearchBox filters={filters} setFilters={setFilters} search={search}/>
 </section>
 <Reveal className="marquee"><div>LOCAL PEOPLE <span>✦</span> HIDDEN PLACES <span>✦</span> REAL STORIES <span>✦</span> ZERO TOURIST TRAPS <span>✦</span> LOCAL PEOPLE <span>✦</span></div></Reveal>
 <section className="bento" id="why"><Reveal className="bentoIntro"><span className="kicker">A better way to explore</span><h2>One trip.<br/><em>Two ways in.</em></h2><p>You choose the level of local. We handle the details.</p></Reveal><Reveal className="bentoGuide"><div className="bentoIcon"><UserRound/></div><span className="micro">HUMAN-LED · 10% ONLINE</span><h3>Hire a local guide.</h3><p>Trade the checklist for a conversation. Find someone who knows where the good stuff actually is.</p><button onClick={()=>go('guides')}>Meet the locals <ArrowUpRight/></button><div className="bentoPortrait"><div>AK</div><span>Arun · Chennai</span></div></Reveal><Reveal className="bentoPackage"><div className="bentoIcon"><Route/></div><span className="micro">SELF-GUIDED · 100% ONLINE</span><h3>Explore yourself.</h3><p>Curated routes, local tips and just enough structure to keep you moving.</p><button onClick={()=>go('packages')}>Browse journeys <ArrowUpRight/></button><div className="routeLines"><i/><i/><i/><i/></div></Reveal><Reveal className="bentoTrust"><ShieldCheck/><div><b>Designed around trust.</b><span>Clear pricing, visible profiles and secure checkout.</span></div><div className="trustNumbers"><span><strong>4.9</strong><small>avg rating</small></span><span><strong>10%</strong><small>guide advance</small></span><span><strong>100%</strong><small>package paid</small></span></div></Reveal></section>

 <section className="indiaShowcase"><div className="indiaHead"><div><span className="kicker">INDIA, WIDE OPEN</span><h2>From coastal mornings<br/><em>to Himalayan nights.</em></h2><p>Explore a growing atlas of local experiences across India — with real destination photography and place-first discovery.</p></div><button onClick={()=>go('india')}>View all destinations <ArrowUpRight/></button></div><div className="destinationRail">{INDIA_DESTINATIONS.slice(0,10).map((d,i)=><motion.button key={d.id} className="destinationCard" whileHover={{y:-8}} onClick={()=>selectPlace(d)}><SmartPlaceImage place={d} alt={d.name}/><span className="destinationShade"/><div className="destinationInfo"><small>{d.region} · {d.state}</small><h3>{d.name}</h3><b>{d.tag}</b></div><span className="destinationNo">{String(i+1).padStart(2,'0')}</span></motion.button>)}</div></section>
 <Reveal className="editorial"><div className="editorialLabel"><span>01 / THE IDEA</span><ArrowDown/></div><div><h2>Tourism should feel less like a transaction and more like an invitation.</h2><p>LocalLoop connects travelers with people who know the rhythm of a place — and lets them choose how much help they want.</p></div></Reveal>
 <Reveal className="featureRail"><div><ScanLine/><span>01</span><b>Discover</b><p>Search by destination, date, people and language.</p></div><div><Heart/><span>02</span><b>Choose</b><p>Compare people-led tours with digital journeys.</p></div><div><Wallet/><span>03</span><b>Pay clearly</b><p>10% online for guides. 100% online for packages.</p></div><div><BadgeCheck/><span>04</span><b>Go</b><p>Meet your local or open your itinerary and explore.</p></div></Reveal>
 </main>}

function IndiaExplorer({destinations,select}){const [region,setRegion]=useState('All');const regions=['All','North','South','East','West','Central'];const filtered=region==='All'?destinations:destinations.filter(d=>d.region===region);return <main className="page premiumPage indiaPage"><div className="pageHeroPro indiaHero"><div><span className="kicker">THE INDIA ATLAS</span><h1>One country.<br/><em>Endless ways in.</em></h1><p>Choose a city, landmark or landscape. LocalLoop can turn the destination into a guided experience or a self-guided journey.</p></div><div className="indiaStat"><b>{destinations.length}+</b><span>destinations<br/>across India</span></div></div><div className="regionTabs">{regions.map(r=><button key={r} className={region===r?'active':''} onClick={()=>setRegion(r)}>{r}</button>)}</div><div className="indiaGrid">{filtered.map((d,i)=><motion.button key={d.id} className="indiaCard" whileHover={{y:-10}} onClick={()=>select(d)}><SmartPlaceImage place={d} alt={d.name}/><span className="indiaOverlay"/><div className="indiaCardText"><small>{d.state} · {d.region}</small><h3>{d.name}</h3><span>{d.tag}</span></div><b className="indiaIndex">{String(i+1).padStart(2,'0')}</b></motion.button>)}</div><div className="photoCredit">Destination photos are linked to their Wikimedia Commons source pages. Check each source page for the applicable photographer credit and license.</div></main>}
function PlaceDetail({place,back,explore}){
 const [media,setMedia]=useState([]); const motionMedia=MOTION_MEDIA[place.id];
 useEffect(()=>{let live=true;fetchCommonsMedia(place).then(items=>{if(live)setMedia(items)});return()=>{live=false}},[place.id]);
 const gallery=media.length?media:Array.from({length:4},()=>({image:place.image,title:place.name,source:place.source}));
 return <main className="page premiumPage placeDetailPage">
  <button className="back" onClick={back}><ArrowLeft/> Back to India</button>
  <section className="placeHero">
   <div className="placeHeroMedia"><SmartPlaceImage place={place} alt={place.name} loading="eager"/><div className="placeHeroShade"/><div className="placeHeroCopy"><span className="kicker">{place.region} · {place.state}</span><h1>{place.name}</h1><p>{place.tag} · Explore the real place before you book the experience.</p></div></div>
  </section>
  <section className="placeLiveGrid">
   <div className="placeIntro"><span className="kicker">REAL PLACE MEDIA</span><h2>See it moving.<br/><em>Then go feel it.</em></h2><p>LocalLoop now uses destination photography from Wikimedia Commons and, where a suitable clip exists, a short real-motion preview. It is not a live webcam; it is a real place video that loops silently.</p><div className="placeActions"><MagneticButton className="heroCta" onClick={explore}>Plan this destination <ArrowUpRight/></MagneticButton><span className="placeStatus"><i/> MEDIA READY</span></div></div>
   {motionMedia?<div className="liveMediaCard"><video src={motionMedia.video} poster={place.image} autoPlay muted loop playsInline preload="metadata"/><div className="liveMediaShade"/><div className="liveBadge"><span className="pulseDot"/> LIVE MOMENT</div><div className="liveCaption"><b>{motionMedia.caption}</b><a href={motionMedia.source} target="_blank" rel="noreferrer">Media source ↗</a></div></div>:<div className="liveMediaCard stillMotion"><SmartPlaceImage place={place} alt={place.name}/><div className="liveMediaShade"/><div className="liveBadge"><span className="pulseDot"/> REAL PHOTO</div><div className="liveCaption"><b>Real destination photography</b><span>More motion media will appear here when available.</span></div></div>}
  </section>
  <section className="placeGallerySection"><div className="galleryHead"><div><span className="kicker">PLACE GALLERY</span><h2>What you'll actually see.</h2></div><span>{media.length||1} verified media sources</span></div><div className="placeGallery">{gallery.map((m,i)=><a className={'galleryTile g'+(i%4)} key={m.title+i} href={m.source} target="_blank" rel="noreferrer"><img src={m.image} alt={`${place.name} view ${i+1}`} loading="lazy"/><span><small>VIEW {String(i+1).padStart(2,'0')}</small><b>{place.name}</b></span></a>)}</div><p className="photoCredit">Images are loaded from Wikimedia Commons at runtime so each destination can use current, place-specific media. Open a tile to see its source page and license/credit information.</p></section>
  <section className="placeFacts"><div><span>01</span><b>Destination</b><p>{place.name}, {place.state}</p></div><div><span>02</span><b>Experience</b><p>{place.tag}</p></div><div><span>03</span><b>LocalLoop</b><p>Guide or self-guided journey</p></div></section>
 </main>
}

function Choose({go}){return <main className="page premiumPage"><button className="back" onClick={()=>go('home')}><ArrowLeft/> Back</button><div className="centerHero"><span className="kicker">THE CHOICE IS YOURS</span><h1>How do you want<br/><em>to experience it?</em></h1><p>Same destination. Completely different way to feel it.</p></div><div className="choicePro"><motion.button whileHover={{y:-8}} className="choiceProCard guide" onClick={()=>go('guides')}><span className="number">01</span><div className="choiceOrb"><UserRound/></div><span className="micro">HUMAN-LED</span><h3>Hire a local guide</h3><p>A real person. A flexible route. Pay only 10% online, settle the rest in person.</p><b>Find a host <ArrowUpRight/></b></motion.button><motion.button whileHover={{y:-8}} className="choiceProCard pack" onClick={()=>go('packages')}><span className="number">02</span><div className="choiceOrb"><Route/></div><span className="micro">SELF-GUIDED</span><h3>Explore yourself</h3><p>A beautifully planned digital journey. Pay 100% online and start instantly.</p><b>Choose a journey <ArrowUpRight/></b></motion.button></div></main>}
function Guides({data,choose}){return <main className="page premiumPage"><div className="pageHeroPro"><div><span className="kicker">THE PEOPLE</span><h1>Locals, not tour guides.</h1><p>Personalities with a point of view. Pick one and make the city yours.</p></div><div className="ruleBadge"><Banknote/><b>10%</b><span>online advance</span></div></div><div className="guideProGrid">{data.map((g,i)=><Reveal key={g.id}><motion.article className="guidePro" whileHover={{y:-10}} transition={{type:'spring',stiffness:250,damping:22}}><div className="guideVisual"><div className="guideAvatar">{g.name.split(' ').map(x=>x[0]).join('')}</div><div className="guideIndex">0{i+1}</div><span className="available"><i/> AVAILABLE</span></div><div className="guideBody"><div className="guideMeta"><span>{g.city}</span><span><Star fill="currentColor"/> {g.rating} <small>({g.reviews})</small></span></div><h3>{g.name}</h3><p>{g.bio}</p><div className="tags">{g.specialties.map(x=><i key={x}>{x}</i>)}</div><div className="guideFoot"><span><b>₹{g.price}</b> / hour</span><button onClick={()=>choose(g)}>View profile <ArrowUpRight/></button></div></div></motion.article></Reveal>)}</div></main>}
function Guide({g,duration,setDuration,back,confirm}){let total=g.price*duration,a=Math.round(total*.1);return <main className="page premiumPage"><button className="back" onClick={back}><ArrowLeft/> Back to locals</button><div className="detailPro"><section className="profilePro"><div className="profileHero"><div className="profileAvatar">{g.name.split(' ').map(x=>x[0]).join('')}</div><span>LOCAL HOST · {g.city}</span><div className="profileHalo"/></div><span className="kicker">YOUR LOCAL</span><h1>{g.name}</h1><div className="profileStats"><span><Star fill="currentColor"/> {g.rating} <small>{g.reviews} reviews</small></span><span><Clock3/> {g.experience}</span><span><Languages/> {g.languages.join(' · ')}</span></div><p className="profileBio">{g.bio}</p><div className="infoBannerPro"><ShieldCheck/><div><b>Low-risk booking</b><span>Only 10% is charged online. The remaining balance stays with you until you meet your guide.</span></div></div></section><aside className="checkoutPro"><span className="kicker">RESERVE YOUR LOCAL</span><h2>Make it yours.</h2><div className="durationPicker"><button onClick={()=>setDuration(Math.max(1,duration-1))}>−</button><div><b>{duration}</b><span>{duration===1?'hour':'hours'}</span></div><button onClick={()=>setDuration(duration+1)}>+</button></div><div className="priceStack"><span>Total experience <b>₹{total}</b></span><span className="payNow">Pay online now <b>₹{a}</b><small>10%</small></span><span>Pay on tour <b>₹{total-a}</b></span></div><MagneticButton className="payButton" onClick={confirm}><CreditCard/> Pay ₹{a} advance <ArrowUpRight/></MagneticButton><small className="checkoutNote"><ShieldCheck/> Secure Razorpay checkout</small></aside></div></main>}
function Packages({data,choose}){return <main className="page premiumPage"><div className="pageHeroPro"><div><span className="kicker">THE JOURNEYS</span><h1>Go deeper.<br/><em>Without a guide.</em></h1><p>Curated digital experiences for travelers who want freedom with a little local intelligence.</p></div><div className="ruleBadge"><CreditCard/><b>100%</b><span>paid online</span></div></div><div className="packageProGrid">{data.map((p,i)=><Reveal key={p.id}><motion.article className="packagePro" whileHover={{y:-10}}><div className={'packageArt '+p.type.toLowerCase()} style={{backgroundImage:`linear-gradient(180deg,rgba(4,35,34,.05),rgba(4,35,34,.75)),url(${imageForPlace(p.city)})`}}><div className="artGrid"/><span>{p.type}</span><b>0{i+1}</b></div><div className="packageBody"><div className="packageMeta"><span>{p.city}</span><span><Clock3/> {p.duration}</span></div><h3>{p.title}</h3><p>{p.places.join(' · ')}</p><div className="packageFoot"><span><b>₹{p.price}</b> / person</span><button onClick={()=>choose(p)}>Open journey <ArrowUpRight/></button></div></div></motion.article></Reveal>)}</div></main>}
function Package({p,people,back,confirm}){let total=p.price*people;return <main className="page premiumPage"><button className="back" onClick={back}><ArrowLeft/> Back to journeys</button><div className="detailPro packageDetail"><section><div className={'packageArt large '+p.type.toLowerCase()} style={{backgroundImage:`linear-gradient(180deg,rgba(4,35,34,.02),rgba(4,35,34,.7)),url(${imageForPlace(p.city)})`}}><div className="artGrid"/><span>{p.type}</span></div><span className="kicker">DIGITAL EXPERIENCE</span><h1>{p.title}</h1><p className="lead">{p.city} · {p.duration}</p><h3 className="sectionTitle">The route</h3><div className="timeline">{p.places.map((x,i)=><div key={x}><span>0{i+1}</span><i/><b>{x}</b></div>)}</div><div className="infoBannerPro"><CreditCard/><div><b>Full payment, zero ambiguity</b><span>This journey is confirmed only after the entire amount is paid online.</span></div></div></section><aside className="checkoutPro"><span className="kicker">CHECKOUT</span><h2>You're one click away.</h2><div className="guestLine"><Users/><span>{people} {people===1?'person':'people'}</span><small>from your search</small></div><div className="priceStack"><span>Price per person <b>₹{p.price}</b></span><span className="payNow"><b>Total due online</b><b>₹{total}</b></span></div><MagneticButton className="payButton" onClick={confirm}><CreditCard/> Pay ₹{total} securely <ArrowUpRight/></MagneticButton><small className="checkoutNote"><ShieldCheck/> 100% online payment</small></aside></div></main>}
function Confirmation({b,go}){return <main className="page confirmPro"><motion.div className="successRing" initial={{scale:.5,opacity:0}} animate={{scale:1,opacity:1}}><CheckCircle2 size={62}/></motion.div><span className="kicker">BOOKING CONFIRMED</span><h1>You're in.</h1><p>{b.kind==='guide'?'Your local is waiting. The remaining balance is paid in person on the tour.':'Your digital journey is fully paid and ready when you are.'}</p><div className="receiptPro"><span>BOOKING CODE <b>{b.bookingCode}</b></span><hr/><div><label>Experience</label><b>{b.title}</b></div><div><label>Total</label><b>₹{b.total}</b></div><div><label>{b.kind==='guide'?'Paid online · 10%':'Paid online · 100%'}</label><b>₹{b.advance}</b></div><div><label>Remaining</label><b>₹{b.kind==='guide'?b.remaining:0}</b></div></div><MagneticButton className="heroCta" onClick={()=>go('home')}>Back to discovery <ArrowUpRight/></MagneticButton></main>}
function Become({onCreated}){const [f,setF]=useState({name:'',city:'Chennai',languages:'English,Tamil',experience:'2 years',price:1000,specialties:'Heritage,Food',bio:'Local guide'}),[msg,setMsg]=useState('');const submit=async e=>{e.preventDefault();const r=await fetch(API+'/guides',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)return setMsg(d.error);setMsg('Guide created successfully.');setTimeout(onCreated,500)};return <main className="page premiumPage center"><span className="kicker">BECOME A GUIDE</span><h1>Turn local knowledge<br/><em>into income.</em></h1><p className="lead">Create a profile, get discovered and earn from the places you already know.</p><form className="formPro" onSubmit={submit}>{Object.keys(f).map((k,i)=><label key={k}><span>{k}</span><input required value={f[k]} placeholder={k} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<MagneticButton type="submit" className="payButton">Create my profile <ArrowUpRight/></MagneticButton>{msg&&<p>{msg}</p>}</form></main>}

createRoot(document.getElementById('root')).render(<App/>);
